apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: database
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userdb;
    USE userdb;
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(100) NOT NULL,
      email VARCHAR(100) NOT NULL
    );